development:
  adapter: mysql2
  encoding: utf8
  database: App42PaaS-Rails-MySQL-Sample_development
  pool: 5
  username: root
  password:

production:
  adapter: mysql2            
  host: 54.208.130.57                         # VM IP
  port: 43666                          # VM Port  
  database: demo_db             # Database Name
  username: aqeex29u40d2i8l1                # User Name
  password: 'apqfx3tyto2490dy0pzy4eiimptv9wf4'             # Password


